export const cartas = [

    {
        "id": 1,
        "nombre": "Cura Chopper",
        "tipo": "Magica",
        "ataque": 0,
        "defensa": 3,
        "energia": 0,
        "habilidad": "Restaura 3 puntos de vida",
        "tripulacion": "",
        "img": "9.png"
    },
    {
        "id": 2,
        "nombre": "Cura Hiriluk",
        "tipo": "Magica",
        "ataque": 0,
        "defensa": 5,
        "energia": 0,
        "habilidad": "Restaura 5 puntos de vida",
        "tripulacion": "",
        "img": "10.png"
    },
    {
        "id": 3,
        "nombre": "Defensa Franky Shogun",
        "tipo": "Magica",
        "ataque": 0,
        "defensa": 7,
        "energia": 0,
        "habilidad": "Aumenta la defensa de un personaje en 7",
        "tripulacion": "",
        "img": "11.png"
    },
    {
        "id": 4,
        "nombre": "Dial de Impacto",
        "tipo": "Magica",
        "ataque": 1,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Quita 1 puntos de vida",
        "tripulacion": "",
        "img": "12.png"
    },
    {
        "id": 5,
        "nombre": "Dial de Impacto",
        "tipo": "Magica",
        "ataque": 1,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Quita 1 puntos de vida",
        "tripulacion": "",
        "img": "12.png"
    },
    {
        "id": 6,
        "nombre": "Dial de Impacto",
        "tipo": "Magica",
        "ataque": 1,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Quita 1 puntos de vida",
        "tripulacion": "",
        "img": "12.png"
    },
    {
        "id": 7,
        "nombre": "Dial de Impacto",
        "tipo": "Magica",
        "ataque": 1,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Quita 1 puntos de vida",
        "tripulacion": "",
        "img": "12.png"
    },
    {
        "id": 8,
        "nombre": "Dial de Impacto",
        "tipo": "Magica",
        "ataque": 1,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Quita 1 puntos de vida",
        "tripulacion": "",
        "img": "12.png"
    },
    {
        "id": 9,
        "nombre": "Enma",
        "tipo": "Magica",
        "ataque": 3,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta 3 puntos de ataque a una carta personaje",
        "tripulacion": "",
        "img": "13.png"
    },
    {
        "id": 10,
        "nombre": "Murakumogiri",
        "tipo": "Magica",
        "ataque": 5,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta 5 puntos de ataque a una carta personaje",
        "tripulacion": "",
        "img": "14.png"
    },
    {
        "id": 11,
        "nombre": "Monkey D. Luffy",
        "tipo": "Personaje",
        "ataque": 10,
        "defensa": 5,
        "energia": 7,
        "habilidad": "Red Hawk",
        "tripulacion": "Sombrero de Paja",
        "img": "0.png"
    },
    {
        "id": 12,
        "nombre": "Roronoa Zoro",
        "tipo": "Personaje",
        "ataque": 8,
        "defensa": 6,
        "energia": 6,
        "habilidad": "Santoryu: Oni Giri",
        "tripulacion": "Sombrero de Paja",
        "img": "1.png"
    },
    {
        "id": 13,
        "nombre": "Vinsmoke Sanji",
        "tipo": "Personaje",
        "ataque": 4,
        "defensa": 4,
        "energia": 4,
        "habilidad": "Diable Jambe",
        "tripulacion": "Sombrero de Paja",
        "img": "2.png"
    },
    {
        "id": 14,
        "nombre": "Nami",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 3,
        "energia": 2,
        "habilidad": "Clima Tact",
        "tripulacion": "Sombrero de Paja",
        "img": "3.png"
    },
    {
        "id": 15,
        "nombre": "Nami",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 3,
        "energia": 2,
        "habilidad": "Clima Tact",
        "tripulacion": "Sombrero de Paja",
        "img": "3.png"
    },
    {
        "id": 16,
        "nombre": "Nami",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 3,
        "energia": 2,
        "habilidad": "Clima Tact",
        "tripulacion": "Sombrero de Paja",
        "img": "3.png"
    },
    {
        "id": 17,
        "nombre": "Nami",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 3,
        "energia": 2,
        "habilidad": "Clima Tact",
        "tripulacion": "Sombrero de Paja",
        "img": "3.png"
    },
    {
        "id": 18,
        "nombre": "Usopp",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Kabuto",
        "tripulacion": "Sombrero de Paja",
        "img": "4.png"
    },
    {
        "id": 19,
        "nombre": "Usopp",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Kabuto",
        "tripulacion": "Sombrero de Paja",
        "img": "4.png"
    },
    {
        "id": 20,
        "nombre": "Usopp",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Kabuto",
        "tripulacion": "Sombrero de Paja",
        "img": "4.png"
    },
    {
        "id": 21,
        "nombre": "Usopp",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Kabuto",
        "tripulacion": "Sombrero de Paja",
        "img": "4.png"
    },
    {
        "id": 22,
        "nombre": "Usopp",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Kabuto",
        "tripulacion": "Sombrero de Paja",
        "img": "4.png"
    },
    {
        "id": 23,
        "nombre": "Nico Robin",
        "tipo": "Personaje",
        "ataque": 4,
        "defensa": 2,
        "energia": 3,
        "habilidad": "Mil Flower",
        "tripulacion": "Sombrero de Paja",
        "img": "5.png"
    },
    {
        "id": 24,
        "nombre": "Tony Tony Chopper",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 4,
        "energia": 2,
        "habilidad": "Monster Point",
        "tripulacion": "Sombrero de Paja",
        "img": "6.png"
    },
    {
        "id": 25,
        "nombre": "Tony Tony Chopper",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 4,
        "energia": 2,
        "habilidad": "Monster Point",
        "tripulacion": "Sombrero de Paja",
        "img": "6.png"
    },
    {
        "id": 26,
        "nombre": "Tony Tony Chopper",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 4,
        "energia": 2,
        "habilidad": "Monster Point",
        "tripulacion": "Sombrero de Paja",
        "img": "6.png"
    },
    {
        "id": 27,
        "nombre": "Tony Tony Chopper",
        "tipo": "Personaje",
        "ataque": 2,
        "defensa": 4,
        "energia": 2,
        "habilidad": "Monster Point",
        "tripulacion": "Sombrero de Paja",
        "img": "6.png"
    },
    {
        "id": 28,
        "nombre": "Franky",
        "tipo": "Personaje",
        "ataque": 6,
        "defensa": 6,
        "energia": 5,
        "habilidad": "Franky Radical Beam",
        "tripulacion": "Sombrero de Paja",
        "img": "7.png"
    },
    {
        "id": 30,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 31,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 32,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 33,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 34,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 35,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 36,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 37,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 38,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 39,
        "nombre": "Campo Mugiwara",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los Sombrero de Paja en 1",
        "tripulacion": "Sombrero de Paja",
        "img": "8.png"
    },
    {
        "id": 40,
        "nombre": "Almirante Akainu",
        "tipo": "Personaje",
        "ataque": 8,
        "defensa": 4,
        "energia": 7,
        "habilidad": "Magu Magu no Mi",
        "tripulacion": "Marina",
        "img": "15.png"
    },
    {
        "id": 41,
        "nombre": "Almirante Kizaru",
        "tipo": "Personaje",
        "ataque": 7,
        "defensa": 4,
        "energia": 6,
        "habilidad": "Pika Pika no Mi",
        "tripulacion": "Marina",
        "img": "16.png"
    },
    {
        "id": 42,
        "nombre": "Smoker",
        "tipo": "Personaje",
        "ataque": 5,
        "defensa": 3,
        "energia": 4,
        "habilidad": "Moku Moku no Mi",
        "tripulacion": "Marina",
        "img": "17.png"
    },
    {
        "id": 43,
        "nombre": "Almirante Kuzan",
        "tipo": "Personaje",
        "ataque": 7,
        "defensa": 4,
        "energia": 6,
        "habilidad": "Hie Hie no Mi",
        "tripulacion": "Marina",
        "img": "18.png"
    },
    {
        "id": 44,
        "nombre": "Almirante Fujitora",
        "tipo": "Personaje",
        "ataque": 8,
        "defensa": 1,
        "energia": 6,
        "habilidad": "Zushi Zushi no Mi",
        "tripulacion": "Marina",
        "img": "19.png"
    }, {
        "id": 46,
        "nombre": "Donquixote Doflamingo",
        "tipo": "Personaje",
        "ataque": 6,
        "defensa": 3,
        "energia": 4,
        "habilidad": "Jaula de pajaros",
        "tripulacion": "Marina",
        "img": "20.png"
    },
    {
        "id": 47,
        "nombre": "Tashigi",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Tatsumaki",
        "tripulacion": "Marina",
        "img": "21.png"
    },
    {
        "id": 48,
        "nombre": "Tashigi",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Tatsumaki",
        "tripulacion": "Marina",
        "img": "21.png"
    },
    {
        "id": 49,
        "nombre": "Tashigi",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Tatsumaki",
        "tripulacion": "Marina",
        "img": "21.png"
    },
    {
        "id": 50,
        "nombre": "Tashigi",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Tatsumaki",
        "tripulacion": "Marina",
        "img": "21.png"
    },
    {
        "id": 51,
        "nombre": "Tashigi",
        "tipo": "Personaje",
        "ataque": 1,
        "defensa": 3,
        "energia": 1,
        "habilidad": "Tatsumaki",
        "tripulacion": "Marina",
        "img": "21.png"
    },
    {
        "id": 52,
        "nombre": "Almirante Garp",
        "tipo": "Personaje",
        "ataque": 3,
        "defensa": 8,
        "energia": 3,
        "habilidad": "Puño de amor",
        "tripulacion": "Marina",
        "img": "22.png"
    },
    {
        "id": 53,
        "nombre": "Almirante Garp",
        "tipo": "Personaje",
        "ataque": 3,
        "defensa": 8,
        "energia": 3,
        "habilidad": "Puño de amor",
        "tripulacion": "Marina",
        "img": "22.png"
    },
    {
        "id": 54,
        "nombre": "Almirante Garp",
        "tipo": "Personaje",
        "ataque": 3,
        "defensa": 8,
        "energia": 3,
        "habilidad": "Puño de amor",
        "tripulacion": "Marina",
        "img": "22.png"
    },
    {
        "id": 55,
        "nombre": "Almirante Garp",
        "tipo": "Personaje",
        "ataque": 3,
        "defensa": 8,
        "energia": 3,
        "habilidad": "Puño de amor",
        "tripulacion": "Marina",
        "img": "22.png"
    },
    {
        "id": 56,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 57,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 58,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 59,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 60,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 61,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 62,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 63,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 64,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 65,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
    {
        "id": 66,
        "nombre": "Campo Marina",
        "tipo": "Campo",
        "ataque": 0,
        "defensa": 0,
        "energia": 0,
        "habilidad": "Aumenta la energía de los personajes de la Marina en 1",
        "tripulacion": "Marina",
        "img": "23.png"
    },
]